name: hairfly
description: A booking app for salon.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  get: ^4.6.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  flutter_easyloading: ^3.0.3
  geolocator: ^8.2.0
  firebase_storage: ^10.2.9
  responsive_builder: ^0.4.2
  url_strategy: ^0.2.0
  get_storage: ^2.0.3
  table_calendar: ^3.0.4
  carousel_slider: ^4.0.0
  convex_bottom_bar: ^3.0.0
  flutter_map: ^0.14.0
  cached_network_image: ^3.2.0
  latlong2: ^0.8.1
  maps_launcher: ^2.0.1
  flutter_rating_bar: ^4.0.0
  flutter_switch: ^0.3.2
  toggle_switch: ^1.4.0
  image_picker: ^0.8.4+9
  path_provider: ^2.0.9
  dio: ^4.0.4
  dot_navigation_bar: ^1.0.1+3
  crop_your_image: ^0.6.0+1
  custom_radio_grouped_button: ^2.1.1
  intl: ^0.17.0
  timelines: ^0.1.0
  outline_search_bar: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
