// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-9plsqpEG026yoaj8uFWpvtwZ50_K0-o',
    appId: '1:512915135865:web:2372a6ec2e6164bcf5a3a8',
    messagingSenderId: '512915135865',
    projectId: 'hairfly-69e89',
    authDomain: 'hairfly-69e89.firebaseapp.com',
    storageBucket: 'hairfly-69e89.appspot.com',
    measurementId: 'G-E0PQ9D1KLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi629wNPCZwTEjqRcjAlBggC_8Lmd50is',
    appId: '1:512915135865:android:e4b385188c272358f5a3a8',
    messagingSenderId: '512915135865',
    projectId: 'hairfly-69e89',
    storageBucket: 'hairfly-69e89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRTiQK9_qz_eg-228A9mvL1XeUtxRxNkw',
    appId: '1:512915135865:ios:df936b97b943d881f5a3a8',
    messagingSenderId: '512915135865',
    projectId: 'hairfly-69e89',
    storageBucket: 'hairfly-69e89.appspot.com',
    iosClientId: '512915135865-1dp133lv8lgpoff75be2ua0nk0j4jc7s.apps.googleusercontent.com',
    iosBundleId: 'com.hairfly.app',
  );
}
